In [1]:
import numpy as np
# In Python we need to use brackets to return the rows or columns .
# WWith Numpy the first array/column starts with 0.
# The values before the comma stands for the rows .
# The value on the right stands for the columns.
# If we want to select a column we have to add : before the column index.
# : means we want all the rows from the selected column.

In [2]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# First row 
a[0]

array([1, 2, 3])

In [4]:
#second row
a[1]

array([4, 5, 6])

In [9]:
a[1,2]  # a[1][2] element.

6

In [5]:
# First column
a[:,0]

array([1, 4])

In [6]:
#All columns
a[:]  

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Second column
a[:,1]

array([2, 5])

In [8]:
# Third column
a[:,2]

array([3, 6])

In [10]:
a[1,1]

5