In [2]:
import numpy as np
# When we want to convert input to array then we use asarray() fuction.
# Inputs could be tuples , list.
# Syntax:
# numpy.asarray(data,dtype=None,order=None)[source]
# data : Data that you want to convert to an array.
# dtype : This is an optional argument . If it is not specified data type will be inferred from input.
# Order : Default is 'c' which is essential row style otherwise we can use 'F' for (Fortran-style)

In [4]:
a=np.matrix(np.ones((2,2)))

In [5]:
np.asarray(a)[1]=2 #The value of second row is changed to 2.
a

matrix([[1., 1.],
        [2., 2.]])

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
np.asarray(a)[2,3]=19
a

matrix([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 19.],
        [ 0.,  0.,  0.,  0.]])

In [9]:
np.asarray(a)[3]=9
a

matrix([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [19., 19., 19., 19.],
        [ 9.,  9.,  9.,  9.]])

In [10]:
np.asarray(a)[1]=6
a

matrix([[ 0.,  0.,  0.,  0.],
        [ 6.,  6.,  6.,  6.],
        [19., 19., 19., 19.],
        [ 9.,  9.,  9.,  9.]])

In [9]:
l1=[1,2,3,4]
t1=(5,6,7,8)
np.asarray(l1)

array([1, 2, 3, 4])

In [10]:
np.array(l1)

array([1, 2, 3, 4])