In [1]:
import numpy as np
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [2]:
t1=(1,2,3,4)
t1

(1, 2, 3, 4)

In [3]:
a=np.array(l1) #creating a numpy array using np.array(object to be made array e.g. list,tuple etc.)
a

array([1, 2, 3, 4])

In [4]:
b=np.array(t1) #converting tuple into array.
t1

(1, 2, 3, 4)

In [6]:
type(b) #type of b is numpy array.


numpy.ndarray

In [7]:
type(a) #type of a is numpy array.

numpy.ndarray

In [8]:
type(t1) #t1 is tuple as initialised.

tuple

In [9]:
type(l1) #l1 is list as initialised.

list

In [10]:
a+2 #'+' adds the item after + operator to each item of array.

array([3, 4, 5, 6])

In [11]:
a*2#'*' multiplies the item after * operator to each item of array.

array([2, 4, 6, 8])

In [12]:
a-2 #'-' subtracts the item after - operator to each item of array.

array([-1,  0,  1,  2])

In [13]:
a/2 #'/' divides the item after / operator to each item of array.

array([0.5, 1. , 1.5, 2. ])

In [14]:
#Shape of array
c=np.array([1,2,3])
c.shape  #Gives the shape of array.

(3,)

In [15]:
#datatype of array
c.dtype #Gives datatype of array.

dtype('int32')

In [16]:
d=np.array([1.1,2.0,3.2])
d.dtype

dtype('float64')

In [17]:
a=np.array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [18]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
a.shape

(1, 4, 3)