In [2]:
import numpy as np
#Numpy zeros() is used to create a matrix full of zeroes.
#Syntax is 
#numpy.zeros(shape,dtype=float,order='C')
#shape: shape of array
#dtype: it is datatype .It is optionaland its defualt value is float64.
#Order: Default is "c" which is essential row style.

In [3]:
np.zeros((2,2)) #(2,2) is shape of array , default dtype is float64.

array([[0., 0.],
       [0., 0.]])

In [4]:
np.zeros((2,2),dtype=np.int16) # Here we have mentioned dtype so output is in integer dtype.

array([[0, 0],
       [0, 0]], dtype=int16)

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [7]:
np.zeros((2,4),dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [8]:
np.zeros((2,4).astype(int))

AttributeError: 'tuple' object has no attribute 'astype'