In [1]:
import numpy as np
#Numpy ones() is used to create a matrix full of ones.
#Syntax is 
#numpy.ones(shape,dtype=float,order='C')
#shape: shape of array
#dtype: it is datatype .It is optionaland its defualt value is float64.
#Order: Default is "c" which is essential row style.

In [2]:
np.ones((2,2)) #(2,2) is shape of array , default dtype is float64.

array([[1., 1.],
       [1., 1.]])

In [3]:
np.ones((1,2),dtype=np.int64) # Here we have mentioned dtype so output is in integer dtype.

array([[1, 1]], dtype=int64)

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,5),dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [6]:
np.ones((5,2),dtype=np.int16)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [7]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])