In [1]:
import numpy as np
# When we deal with neural networks we need to flatten data and that can be done using flatten() function.
# Syntax :
# numpy.flatten(order='c')
# Order='c' Default is 'c' which is an essential row.

In [2]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [5]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])