In [1]:
import numpy as np
# To generate random numbers for Gaussian distribution we use numpy.random.normal() function.
# Syntax:
# numpy.random.normal(loc,scale,size)
# loc : The Mean. The center of distribution.
# scale : Standard deviation.
# size : number of returns .

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
randoM=np.random.normal(5,0.5,10) # If we plot ouput of this we will get a normal distribution or bell curve.
randoM

array([5.27637924, 4.49808586, 5.14327502, 5.20391991, 5.52243585,
       5.54468821, 5.21930502, 6.24460446, 4.60006825, 4.99298599])

In [4]:
randoM=np.random.normal(9,0.5,10)
randoM

array([8.38237806, 8.50953291, 9.27182319, 9.50692673, 8.76797819,
       8.42780523, 9.0812492 , 8.67838918, 9.47903011, 9.78897958])