In [1]:
import numpy as np
# To reshape data we can use reshape() funvtion.
# Syntax is:
# numpy.reshape(a,new_Shape,order='C')
# a: Array that we want to reshape.
# new_Shape : The new desired shape.
# Order : Default is C which is an essential row style.

In [2]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.reshape(a,(3,2)) #reshape() the mentioned array to new shape.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])