In [1]:
import numpy as np
# When we want to create values that are evenly spaced within a defined interval we use arange() function.
# Syntax :
# numpy.arange(start,stop,step)
# start : start of interval.
# stop : end of interval.
# step : spacing between values which is 1 by default.

In [3]:
np.arange(1,11) # we are making interval between 1-11 with default step i.e. 1.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(1,8,2)  # we are making interval between 1-11 with default step i.e. 2.

array([1, 3, 5, 7])

In [7]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])