In [1]:
import numpy as np
# With hstack we can append data horizontally
# syntax:
# numpy.hstack((a1,a2))
# a1,a2: Arrays to be appended.

In [2]:
a=np.array([1,2,3,4]) 
a

array([1, 2, 3, 4])

In [3]:
b=np.array([5,6,7,8])
b

array([5, 6, 7, 8])

In [5]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.hstack((b,a))

array([5, 6, 7, 8, 1, 2, 3, 4])